# Generated by Django 4.2.7 on 2023-11-14 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountType',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='recordincomeexpense',
            old_name='dateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='recordincomeexpense',
            old_name='inputType',
            new_name='input_type',
        ),
    ]
