# Generated by Django 4.2.7 on 2023-11-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_account_user_recordincomeexpense_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recordincomeexpense',
            name='account',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='RecordIncomeExpense',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
